### ISSUE TITLE
print_arg error: TypeError: cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by Resolvit-Tech** [jitcor/frida-ios-cipher#1]
Hello sir,

First I want to say thank you for frida-ios-cipher.

![error](https://github.com/Humenger/frida-ios-cipher/assets/148782271/f5ce11ee-927e-4db7-8120-49883531ccea)

error message:
print_arg error: TypeError: cannot read property 'toString' of undefined
    at t (frida/runtime/hexdump.js:20)
    at M (agent/index.ts:240)
    at onEnter (agent/index.ts:381)
    
    
 Do you have discord or line? your gmail does not work.

**Comment by eyJhb** [comment]
Typically happens, when trying to read from a address that is not possible, ie. `0x0`.

**Comment by yml2213** [comment]
me too

**Comment by wevve** [comment]
一样的问题， 
`frida                     16.4.5
frida-tools               12.5.0`

**Comment by cz43608970** [comment]
Same. How to fix it?

**Comment by eyJhb** [comment]
Check if addr is `0x0`, ie. https://github.com/jitcor/frida-ios-cipher/blob/2e11a06e082ac7ed956d9528d0fc19cc92629205/agent/index.ts#L199

```ts
function print_arg(addr,len=240) {
    try {
        if(addr==null)return "\n";
        if(addr==0x0)return "\n";
        return "\n"+(hexdump(addr,{length:len})) + "\n";
    } catch (e) {
        if(e instanceof Error){
            console.error("print_arg error:",e.stack);
        }
        return addr + "\n";
    }
}
```

**Comment by jitcor** [comment]
This is normal and will not affect other print data. It can be ignored for now.
