### ISSUE TITLE
 HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by xzpqaa** [jitcor/frida-ios-cipher#4]
❯ frida -U --codeshare frida-ios-cipher -f "com.xxxx.xxxx" 
     ____
    / _  |   Frida 16.5.2 - A world-class dynamic instrumentation toolkit
   | (_| |
    > _  |   Commands:
   /_/ |_|       help      -> Displays the help system
   . . . .       object?   -> Display information about 'object'
   . . . .       exit/quit -> Exit
   . . . .
   . . . .   More info at https://frida.re/docs/home/
   . . . .
   . . . .   Connected to iPhone (id=xxxxxxx)
Spawning `com.xxxx.xxxxx`...                                    
Got an unhandled exception while trying to retrieve frida-ios-cipher - HTTP Error 404: Not Found
Exiting!

Thank you for using Frida!

I have a problem...

**Comment by jitcor** [comment]
Please execute the command correctly.
